load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "constants",
    srcs = ["constants.go"],
    importpath = "github.com/kartones/bazel-gazelle-sample-web-extension/gazelle/constants",
    visibility = ["//visibility:public"],
)
